// frontend/src/components/AppShell.vue
<template>
  <div class="app-shell">
    <aside class="app-sider">
      <div class="brand-block">
        <h1>企业 IT 服务台</h1>
        <p>Vue 3 网页端空页面骨架</p>
      </div>
      <nav class="nav-sections">
        <section v-for="section in menuSections" :key="section.key" class="nav-section">
          <h2>{{ section.label }}</h2>
          <RouterLink
            v-for="item in section.children"
            :key="item.path"
            :to="item.path"
            class="nav-link"
            :class="{ active: route.path === item.path }"
          >
            {{ item.label }}
          </RouterLink>
        </section>
      </nav>
    </aside>
    <main class="app-main">
      <header class="app-header">
        <span>当前只搭页面骨架，具体业务逻辑留空</span>
      </header>
      <section class="app-content">
        <RouterView />
      </section>
    </main>
  </div>
</template>

<script setup>
import { RouterLink, RouterView, useRoute } from "vue-router";

const route = useRoute();

const menuSections = [
  {
    key: "portal",
    label: "员工门户",
    children: [
      { path: "/portal/home", label: "门户首页" },
      { path: "/portal/create", label: "发起申请" },
      { path: "/portal/my-tickets", label: "我的申请" },
      { path: "/portal/pending-confirm", label: "待确认" }
    ]
  },
  {
    key: "approval",
    label: "审批中心",
    children: [
      { path: "/approval/pending", label: "待我审批" },
      { path: "/approval/history", label: "我已审批" },
      { path: "/approval/detail", label: "审批详情" }
    ]
  },
  {
    key: "service-desk",
    label: "服务台作业台",
    children: [
      { path: "/service-desk/home", label: "作业台首页" },
      { path: "/service-desk/pending-assign", label: "待分派" },
      { path: "/service-desk/queue", label: "待抢单" },
      { path: "/service-desk/in-progress", label: "我的处理中" },
      { path: "/service-desk/alerts", label: "超时预警" },
      { path: "/service-desk/detail", label: "工单详情" }
    ]
  },
  {
    key: "admin",
    label: "管理后台",
    children: [
      { path: "/admin/users", label: "用户管理" },
      { path: "/admin/departments", label: "部门管理" },
      { path: "/admin/systems", label: "系统与权限" },
      { path: "/admin/approval-templates", label: "审批模板" },
      { path: "/admin/sla-policies", label: "SLA 规则" },
      { path: "/admin/knowledge", label: "知识库" },
      { path: "/admin/reports", label: "统计报表" },
      { path: "/admin/audit-logs", label: "审计日志" }
    ]
  }
];
</script>

// frontend/src/components/AppShell.jsx
import { Layout, Menu, Typography } from "antd";
import { Link, Outlet, useLocation } from "react-router-dom";

const { Header, Content, Sider } = Layout;

const menuItems = [
  {
    key: "portal",
    label: "员工门户",
    children: [
      { key: "/portal/home", label: <Link to="/portal/home">门户首页</Link> },
      { key: "/portal/create", label: <Link to="/portal/create">发起申请</Link> },
      { key: "/portal/my-tickets", label: <Link to="/portal/my-tickets">我的申请</Link> },
      { key: "/portal/pending-confirm", label: <Link to="/portal/pending-confirm">待确认</Link> }
    ]
  },
  {
    key: "approval",
    label: "审批中心",
    children: [
      { key: "/approval/pending", label: <Link to="/approval/pending">待我审批</Link> },
      { key: "/approval/history", label: <Link to="/approval/history">我已审批</Link> },
      { key: "/approval/detail", label: <Link to="/approval/detail">审批详情</Link> }
    ]
  },
  {
    key: "service-desk",
    label: "服务台作业台",
    children: [
      { key: "/service-desk/home", label: <Link to="/service-desk/home">作业台首页</Link> },
      { key: "/service-desk/pending-assign", label: <Link to="/service-desk/pending-assign">待分派</Link> },
      { key: "/service-desk/queue", label: <Link to="/service-desk/queue">待抢单</Link> },
      { key: "/service-desk/in-progress", label: <Link to="/service-desk/in-progress">我的处理中</Link> },
      { key: "/service-desk/alerts", label: <Link to="/service-desk/alerts">超时预警</Link> },
      { key: "/service-desk/detail", label: <Link to="/service-desk/detail">工单详情</Link> }
    ]
  },
  {
    key: "admin",
    label: "管理后台",
    children: [
      { key: "/admin/users", label: <Link to="/admin/users">用户管理</Link> },
      { key: "/admin/departments", label: <Link to="/admin/departments">部门管理</Link> },
      { key: "/admin/systems", label: <Link to="/admin/systems">系统与权限</Link> },
      { key: "/admin/approval-templates", label: <Link to="/admin/approval-templates">审批模板</Link> },
      { key: "/admin/sla-policies", label: <Link to="/admin/sla-policies">SLA 规则</Link> },
      { key: "/admin/knowledge", label: <Link to="/admin/knowledge">知识库</Link> },
      { key: "/admin/reports", label: <Link to="/admin/reports">统计报表</Link> },
      { key: "/admin/audit-logs", label: <Link to="/admin/audit-logs">审计日志</Link> }
    ]
  }
];

const openKeys = {
  "/portal": "portal",
  "/approval": "approval",
  "/service-desk": "service-desk",
  "/admin": "admin"
};

export function AppShell() {
  const location = useLocation();
  const rootKey = Object.keys(openKeys).find((prefix) => location.pathname.startsWith(prefix));

  return (
    <Layout className="app-shell">
      <Sider width={260} theme="light" className="app-sider">
        <div className="brand-block">
          <Typography.Title level={4}>企业 IT 服务台</Typography.Title>
          <Typography.Paragraph>JS 前端空页面骨架</Typography.Paragraph>
        </div>
        <Menu
          mode="inline"
          selectedKeys={[location.pathname]}
          defaultOpenKeys={rootKey ? [openKeys[rootKey]] : ["portal"]}
          items={menuItems}
        />
      </Sider>
      <Layout>
        <Header className="app-header">
          <Typography.Text>当前只搭页面骨架，具体业务逻辑留空</Typography.Text>
        </Header>
        <Content className="app-content">
          <Outlet />
        </Content>
      </Layout>
    </Layout>
  );
}
